name: Publish

on:
    push:
        branches:
            - main
        paths:
            - 'package.json'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            
            - name: installing vsce
              run: npm i -g vsce
            
            - name: Packageing
              run: vsce package
            
            - name: Publishing
              run: vsce publish
            
            env:
              VSCE_PAT: ${{ secrets.PAT }}
